name: QR Code Generator Workflow

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "Started Running QR FastAPI BE"
            
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Install system dependecies
              run: |
               sudo apt update
               sudo apt install -y libjpeg-dev zlib1g-dev libzbar0

            - name: Install Dependecies
              run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt

            - name: Run Tests
              run: echo 'Test are comming ..'