name: QR Code Generator Workflow

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "Started Running QR FastAPI BE"
            
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            
            - name: Install system dependecies
              run: |
               sudo apt update
               sudo apt install -y libjpeg-dev zlib1g-dev libzbar0

            - name: Install Dependecies
              run: |
               python -m pip install --upgrade pip
               pip install --no-cache-dir -r requirements.txt
               pip install pytest
    
    test:
      needs: build
      runs-on: ubuntu-latest
      steps:
          - name: Run Unit Tests
            run: pytest test_main.py